package edu.baker.project10;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

/**
 * Unit tests for CaesarCipher. Because encrypt and decrypt now take and return
 * byte arrays, every test works in memory with no files involved.
 *
 * @author Ahmed Lotfey
 */
public class CaesarCipherTest {

    /**
     * Supplies (password, expected shift as text) pairs for setPassword.
     * The expected shifts were computed from Java's String.hashCode() with the
     * same formula the cipher uses. The empty password gives a computed shift
     * of 0, which covers the branch that replaces 0 with 3.
     *
     * @return a Stream of Arguments, one per test case
     */
    static Stream<Arguments> passwordData() {
        return Stream.of(
                Arguments.of("", "3"),            // hashCode 0 -> shift 0 -> replaced by 3
                Arguments.of("Bubblegum", "19"),  // hashCode -1592975085 & 127 = 19
                Arguments.of("abc", "98")         // hashCode 96354 & 127 = 98
        );
    }

    /**
     * Verifies that setPassword stores the shift computed from the password,
     * as reported by getPassword. The cipher is created with a different
     * password first, so the test checks setPassword itself, not the constructor.
     *
     * @param password      the password passed to setPassword
     * @param expectedShift the shift amount getPassword should report
     */
    @ParameterizedTest
    @MethodSource("passwordData")
    void setPasswordStoresShiftComputedFromPassword(String password, String expectedShift) {
        CaesarCipher cipher = new CaesarCipher("start");
        cipher.setPassword(password);
        assertEquals(expectedShift, cipher.getPassword());
    }

    /**
     * Verifies that encrypt adds the shift (98 for "abc") to every byte, and that
     * values past 127 wrap around to negative bytes: 127 + 98 = 225, which
     * wraps to -31.
     */
    @Test
    void encryptAddsShiftToEveryByteAndWrapsAround() {
        CaesarCipher cipher = new CaesarCipher("abc");
        byte[] cleartext = {0, 10, 127, -128};
        byte[] expected  = {98, 108, -31, -30};
        assertArrayEquals(expected, cipher.encrypt(cleartext));
    }

    /**
     * Verifies that decrypt subtracts the shift from every byte, turning the
     * ciphertext from the encrypt example back into the original bytes,
     * including the wrapped-around values.
     */
    @Test
    void decryptSubtractsShiftFromEveryByte() {
        CaesarCipher cipher = new CaesarCipher("abc");
        byte[] ciphertext = {98, 108, -31, -30};
        byte[] expected   = {0, 10, 127, -128};
        assertArrayEquals(expected, cipher.decrypt(ciphertext));
    }

    /**
     * Verifies the empty-input boundary: encrypting zero bytes returns an empty
     * array (the loop body never runs) instead of failing.
     */
    @Test
    void encryptOfEmptyArrayReturnsEmptyArray() {
        CaesarCipher cipher = new CaesarCipher("abc");
        assertArrayEquals(new byte[0], cipher.encrypt(new byte[0]));
    }

    /**
     * Property (round trip): for any data and any password, decrypting the
     * encrypted data gives back exactly the original bytes. jqwik runs this
     * with 1000 random byte arrays and passwords.
     *
     * @param data     random bytes generated by jqwik
     * @param password random password generated by jqwik
     */
    @Property
    void decryptUndoesEncrypt(@ForAll byte[] data, @ForAll String password) {
        CaesarCipher cipher = new CaesarCipher(password);
        assertArrayEquals(data, cipher.decrypt(cipher.encrypt(data)));
    }

    /**
     * Property: encryption changes every single byte. The shift is always
     * between 1 and 127, never 0, so no byte can map to itself. This is the
     * unit-level reason the file test in EncryptionTest sees most bytes differ.
     *
     * @param data     random bytes generated by jqwik
     * @param password random password generated by jqwik
     */
    @Property
    void encryptChangesEveryByte(@ForAll byte[] data, @ForAll String password) {
        CaesarCipher cipher = new CaesarCipher(password);
        byte[] ciphertext = cipher.encrypt(data);
        for (int i = 0; i < data.length; i++) {
            assertNotEquals(data[i], ciphertext[i]);
        }
    }
}