package edu.baker.project10;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.constraints.StringLength;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Unit tests for XORCipher. Because encrypt and decrypt now take and return
 * byte arrays, every test works in memory with no files involved.
 *
 * @author Ahmed Lotfey
 */
public class XORCipherTest {

    /**
     * Supplies (password, expected getPassword result) pairs. Plain ASCII
     * passwords come back unchanged. A character whose code fits in 8 bits
     * (e with an accent, code 233) also comes back unchanged. A character above
     * 255 (the euro sign, code 8364) keeps only its low 8 bits (code 172, the
     * not sign), which documents what setPassword really stores.
     *
     * @return a Stream of Arguments, one per test case
     */
    static Stream<Arguments> passwordData() {
        return Stream.of(
                Arguments.of("Bubblegum", "Bubblegum"),  // several ASCII characters
                Arguments.of("k", "k"),                  // single character, shortest valid key
                Arguments.of("\u00e9", "\u00e9"),        // code 233: fits in one byte
                Arguments.of("\u20ac", "\u00ac")         // code 8364: only the low 8 bits (172) are kept
        );
    }

    /**
     * Verifies that setPassword stores one key byte per password character, as
     * reported by getPassword. The cipher is created with a different password
     * first, so the test checks setPassword itself, not the constructor.
     *
     * @param password         the password passed to setPassword
     * @param expectedPassword what getPassword should report afterwards
     */
    @ParameterizedTest
    @MethodSource("passwordData")
    void setPasswordStoresOneKeyBytePerCharacter(String password, String expectedPassword) {
        XORCipher cipher = new XORCipher("start");
        cipher.setPassword(password);
        assertEquals(expectedPassword, cipher.getPassword());
    }

    /**
     * Verifies that encrypt XORs each byte with the password bytes and cycles
     * through the password. With password "ab" (97, 98): 0^97=97, 0^98=98,
     * the third byte reuses 'a' (0^97=97), and 1^98=99.
     */
    @Test
    void encryptXorsEachByteCyclingThroughPassword() {
        XORCipher cipher = new XORCipher("ab");
        byte[] cleartext = {0, 0, 0, 1};
        byte[] expected  = {97, 98, 97, 99};
        assertArrayEquals(expected, cipher.encrypt(cleartext));
    }

    /**
     * Verifies that decrypt turns the ciphertext from the encrypt example back
     * into the original bytes.
     */
    @Test
    void decryptXorsCiphertextBackToCleartext() {
        XORCipher cipher = new XORCipher("ab");
        byte[] ciphertext = {97, 98, 97, 99};
        byte[] expected   = {0, 0, 0, 1};
        assertArrayEquals(expected, cipher.decrypt(ciphertext));
    }

    /**
     * Verifies the empty-input boundary: encrypting zero bytes returns an empty
     * array (the loop body never runs) instead of failing.
     */
    @Test
    void encryptOfEmptyArrayReturnsEmptyArray() {
        XORCipher cipher = new XORCipher("ab");
        assertArrayEquals(new byte[0], cipher.encrypt(new byte[0]));
    }

    /**
     * Property (round trip): for any data and any non-empty password,
     * decrypting the encrypted data gives back exactly the original bytes.
     * An empty password is excluded because the cipher divides by the password
     * length, which is starter behavior the assignment does not ask us to change.
     *
     * @param data     random bytes generated by jqwik
     * @param password random password of at least one character
     */
    @Property
    void decryptUndoesEncrypt(@ForAll byte[] data, @ForAll @StringLength(min = 1) String password) {
        XORCipher cipher = new XORCipher(password);
        assertArrayEquals(data, cipher.decrypt(cipher.encrypt(data)));
    }

    /**
     * Property (XOR undoes itself): encrypting twice with the same password
     * gives back the original data, because (a ^ k) ^ k == a. This property is
     * specific to XOR; it does not hold for the Caesar cipher.
     *
     * @param data     random bytes generated by jqwik
     * @param password random password of at least one character
     */
    @Property
    void encryptingTwiceGivesBackOriginal(@ForAll byte[] data, @ForAll @StringLength(min = 1) String password) {
        XORCipher cipher = new XORCipher(password);
        assertArrayEquals(data, cipher.encrypt(cipher.encrypt(data)));
    }
}